// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Account   string `json:"account"`    //账号
	Password  string `json:"password"`   //密码
	LoginType string `json:"login_type"` //登录方式
	AppId     string `json:"app_id"`     //应用id
	ClientId  string `json:"clientId"`   //客户端id
	Platform  uint   `json:"platform"`   //登录平台
}

type LoginResp struct {
	Expires uint   `json:"expires"` //token过期时间
	Token   string `json:"token"`   //登录票据
	Tag     string `json:"tag"`     //操作标识
}

type GetUserInfoResp struct {
	Uid      uint   `json:"uid"`
	Nickname string `json:"nickname"`
}

type GetUserInfoReq struct {
	Uid uint `json:"uid"`
}
